<a href="https://colab.research.google.com/github/syedmusadiqillahi123/LinearRegression/blob/main/pickle_and_joblib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [ ]:
df = pd.read_csv('/content/homeprices.csv')
df

area   price
0  2600  550000
1  3000  585000
2  3200  610000
3  3600  680000
4  4000  725000

In [ ]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [ ]:
model.coef_

array([130.99315068])

In [ ]:
model.intercept_

200342.46575342462

In [ ]:
model.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([855308.21917808])

In [ ]:
130.99315068*5000+200342.46575342462

855308.2191534247

In [ ]:
import pickle

In [ ]:
with open('model_pickle','wb') as f:
  pickle.dump(model,f)

In [ ]:
with open('model_pickle','rb') as f:
  mp=pickle.load(f)

In [ ]:
mp.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([855308.21917808])

In [ ]:
!pip install  joblib


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import joblib

In [ ]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [ ]:
mj=joblib.load('model_joblib')

In [ ]:
mj.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([855308.21917808])

In [ ]:
mj.coef_

array([130.99315068])

In [ ]:
mj.intercept_

200342.46575342462